### PR TITLE
Fixing 'Author' field

### PR DESCRIPTION
**Pull request by imriss**
To fix this error:

* checking for file 'qdap-master/DESCRIPTION' ... ERROR
Required field missing or empty:
  'Author'
* DONE

### CODE REVIEW

**Comment by Dasonk** [comment]
This seems like a step backwards? Note this from Writing R Extensions: "Both ‘Author’ and ‘Maintainer’ fields can be omitted if a suitable ‘Authors@R’ field is given" and Authors@R is currently being used.  Unless I'm mistaken the Author and Maintainer fields will  be autogenerated on CRAN if you'e using Authors@R.

**Comment by trinker** [comment]
Thank you for the PR.  CRAN checks do not indicate the following is an error:

```
checking for file 'qdap-master/DESCRIPTION' ... ERROR
Required field missing or empty:
'Author'
```

As @Dasonk suggests the DESCRIPTION file is formatted per Writing R Extensions.  Can you tell us where you got the error you mentioned?   In other words, was it during install (if so from GitHub or CRAN), R check in the build process, etc.?

**Comment by imriss** [comment]
@Dasonk @trinker:
Thank you for your reply. 
I was getting the error when installing the package from the github/archive/zip file. Now, I switched to installation via CRAN, and everything is fine.

**Comment by Dasonk** [comment]
@imriss Were you literally just trying to use the zip of the repository to install the package? That shouldn't work for most packages.  If you want to install from github I suggest using `devtools::install_github("trinker/qdap")` or `remotes::install_github("trinker/qdap")` depending on if one or the other is on your system.

**Comment by imriss** [comment]
@Dasonk `devtools::install_github("trinker/qdap")` worked for me. Thanks.

**Comment by imriss** [comment]
For the reference, to prepare the `Java `config on an `Arch Linux` system, the steps were:

```
yaourt -S jdk8-openjdk jdk7-openjdk 
sudo R CMD javareconf
sudo R
devtools::install_github("trinker/qdap")
```

**Comment by Dasonk** [comment]
The issue is closed but your last comment has a few issues.  Just so you know you don't necessarily need yaourt to install from 'extra' (and actually yaourt is quite outdated and it's recommended to use a different aur helper if you want to go that route).  You only need one or the other of the jdks - I'm not sure why you're grabbing both as only one will be used.  You do need to run the javareconf command.  You shouldn't be launching R with sudo though.

**Pull request closed without merging**
